pipeline {
  agent any


  environment {
    // Optional: Set these if you integrate with external tools later
    // SONAR_HOST_URL = 'http://localhost:9000'
    // SONAR_TOKEN = credentials('sonar-token')
  }

  stages {
    stage('Prep Wrapper') {
      steps {
        sh 'chmod +x ./gradlew'
      }
    }

    stage('Build') {
      steps {
        sh './gradlew clean assemble'
      }
    }

    stage('Unit Tests') {
      steps {
        sh './gradlew test'
      }
      post {
        always {
          junit 'build/test-results/test/*.xml'
        }
      }
    }

    stage('Static Analysis') {
      steps {
        sh './gradlew sonarqube'
      }
    }

    stage('Security Scan') {
      steps {
        sh './gradlew dependencyCheckAnalyze'
      }
    }

    stage('Performance Testing') {
      steps {
        sh './gradlew runPerfTests'
      }
    }

    stage('Javadocs') {
      steps {
        sh './gradlew javadoc'
      }
    }
  }
}
